$background = 020305
$onBackground = e3e5ef
$surface = 020305
$surfaceDim = 020305
$surfaceBright = 0b0d11
$surfaceContainerLowest = 000000
$surfaceContainerLow = 030407
$surfaceContainer = 05070a
$surfaceContainerHigh = 07090d
$surfaceContainerHighest = 090b0f
$onSurface = e3e5ef
$surfaceVariant = 090b0f
$onSurfaceVariant = a8abb5
$outline = 72757e
$outlineVariant = 444850
$inverseSurface = f9f9fe
$inverseOnSurface = 545559
$shadow = 000000
$scrim = 000000
$surfaceTint = 212835
$primary = b4c7ed
$primaryDim = a6b9df
$onPrimary = 2d4160
$primaryContainer = 405373
$onPrimaryContainer = d7e3ff
$inversePrimary = 4d6080
$primaryFixed = bfd2f9
$primaryFixedDim = b1c4ea
$onPrimaryFixed = 213553
$onPrimaryFixedVariant = 3e5171
$secondary = bdc7dc
$secondaryDim = b0b9ce
$onSecondary = 374052
$secondaryContainer = 323c4d
$onSecondaryContainer = b6bfd5
$secondaryFixed = d9e3f9
$secondaryFixedDim = cbd4ea
$onSecondaryFixed = 364051
$onSecondaryFixedVariant = 525c6e
$tertiary = eaddff
$tertiaryDim = deccfd
$onTertiary = 584b74
$tertiaryContainer = deccfd
$onTertiaryContainer = 50426b
$tertiaryFixed = deccfd
$tertiaryFixedDim = d0bfef
$onTertiaryFixed = 3c2f56
$onTertiaryFixedVariant = 594b75
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 65789a
$secondaryPaletteKeyColor = 6e778a
$tertiaryPaletteKeyColor = 7f709c
$neutralPaletteKeyColor = 76777c
$neutralVariantPaletteKeyColor = 747780
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 65789a
$secondary_paletteKeyColor = 6e778a
$tertiary_paletteKeyColor = 7f709c
$neutral_paletteKeyColor = 76777c
$neutral_variant_paletteKeyColor = 747780
$term0 = 080808
$term1 = 8582ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 8aaed3
$term5 = 9ca5ef
$term6 = 94d0fa
$term7 = e8d3de
$term8 = ac9fa9
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = adc3d9
$term13 = b6baf8
$term14 = b6e1ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = e2e0f5
$pink = d6dbff
$mauve = a9beff
$red = a7adff
$maroon = b8baf1
$peach = e0c2f9
$yellow = d0f9f4
$green = c1e4ff
$teal = c7e3ff
$sky = c2ddff
$sapphire = a2caff
$blue = 98beff
$lavender = b6cdff
$klink = 5589ce
$klinkSelection = 5489ce
$kvisited = 5e7bdd
$kvisitedSelection = 5d7bdd
$knegative = 7778ff
$knegativeSelection = 7678ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b4ff
$kpositiveSelection = 00b4fe
$text = e3e5ef
$subtext1 = a8abb5
$subtext0 = 72757e
$overlay2 = 191919
$overlay1 = 161617
$overlay0 = 121315
$surface2 = 0e0f11
$surface1 = 090b0d
$surface0 = 030406
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
